import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import client from '../client';
import groq from 'groq';

import Header from '#Organisms/Header';
import Main from '#Organisms/Main';
import Footer from '#Organisms/Footer';

export default function Home({hero, sections}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header hero={hero}/>
      <Main sections={sections}/>
      <Footer/>
    
    </div>
  )
}


export async function getStaticProps(params) {
  
  const data = await client.fetch(
    groq`
      *[_type == "route"][0]{
       page ->{
        hero,
        content
      }
      }
    `
  )

  console.log(data)


  return { props: {
    hero: data.page.hero,
    sections: data.page.content ? data.page.content : []
  }}
}