import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import client from '../client';
import groq from 'groq';

import Header from '#Organisms/Header';
import Main from '#Organisms/Main';
import Footer from '#Organisms/Footer';

export default function Home({hero, sections, navigation}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header hero={hero} navigation={navigation}/>
      <Main sections={sections}/>
      <Footer/>
    
    </div>
  )
}


export async function getStaticProps({locale, defaultLocale}) {

  const clientConfig = {...client.config(), token: process.env.SANITY_TOKEN}
  client.config(clientConfig)

  const data = await client.fetch(
    groq`
      *[_type == "page" && __i18n_lang == "${locale}"][0]{
        hero,
        content,
        navigation
      }
    `
  )

  return { props: {
    hero: data.hero,
    sections: data.content ? data.content : [],
    navigation: data.navigation ? data.navigation : []
  }}
}